[database]
port = {{ env "GOBID_DATABASE_PORT"  }}
host = {{ env "GOBID_DATABASE_HOST"  }}
user = {{ env "GOBID_DATABASE_USER"  }}
password = {{ env "GOBID_DATABASE_PASSWORD" }}
database = {{ env "GOBID_DATABASE_NAME"  }}